/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class cn_ylcto_octcplus_OCTRecognition */

#ifndef _Included_cn_ylcto_octcplus_OCTRecognition
#define _Included_cn_ylcto_octcplus_OCTRecognition
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_ylcto_octcplus_OCTRecognition
 * Method:    OctRecognition
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_ylcto_octcplus_OCTRecognition_OctRecognition
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
